"""extend auth_audit_event_type for role permission assignment

Revision ID: 1d509f51cca2
Revises: a6f7293e7d51
Create Date: 2026-08-06 05:39:53.349424

Hand-written, not autogenerated — same reasoning as every prior
AuditEventType extension in this project (22faf2677ebe, 642dc9d7eb70,
a6f7293e7d51): Alembic's autogenerate does not diff the SQL body of an
existing named CHECK constraint backing `sa.Enum(..., native_enum=False,
create_constraint=True)`. Adds PERMISSION_GRANTED/PERMISSION_REVOKED (28
total allowed values) for the Role <-> Permission Assignment module
(Phase 5 Step 5). No column type or length change is needed — the
column is already VARCHAR(30), and both new values fit comfortably.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d509f51cca2"
down_revision: str | None = "a6f7293e7d51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREVIOUS_EVENT_TYPE_VALUES = (
    "login_success",
    "login_failed",
    "logout",
    "password_changed",
    "password_reset_requested",
    "password_reset_completed",
    "token_refreshed",
    "token_revoked",
    "token_reuse_detected",
    "account_locked",
    "account_unlocked",
    "role_assigned",
    "role_revoked",
    "user_created",
    "user_updated",
    "user_deleted",
    "user_activated",
    "user_deactivated",
    "password_reset_by_admin",
    "password_change_forced",
    "role_created",
    "role_updated",
    "role_deleted",
    "permission_created",
    "permission_updated",
    "permission_deleted",
)
_NEW_EVENT_TYPE_VALUES = (
    "permission_granted",
    "permission_revoked",
)


def _event_type_in_clause(values: tuple[str, ...]) -> str:
    return "event_type IN (" + ", ".join(f"'{value}'" for value in values) + ")"


def upgrade() -> None:
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _event_type_in_clause(_PREVIOUS_EVENT_TYPE_VALUES + _NEW_EVENT_TYPE_VALUES),
    )


def downgrade() -> None:
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _event_type_in_clause(_PREVIOUS_EVENT_TYPE_VALUES),
    )
