"""extend auth_audit_event_type for user management events

Revision ID: 22faf2677ebe
Revises: da6db356e430
Create Date: 2026-08-06 02:44:28.357196

Hand-written, not autogenerated: `auth_audit_log.event_type` uses
`sa.Enum(..., native_enum=False, create_constraint=True)`, which Postgres
stores as a plain VARCHAR plus a CHECK constraint (see app/modules/auth/
models.py's module docstring for why `native_enum=False` was chosen).
Alembic's autogenerate does not diff the SQL body of existing named CHECK
constraints (confirmed via `alembic check` reporting no drift after this
enum's Python-side values were extended), so this migration drops and
recreates the constraint by hand with the expanded value list, matching
the 7 new `AuditEventType` members added for the User Management module
(Phase 5 Step 2): USER_CREATED, USER_UPDATED, USER_DELETED,
USER_ACTIVATED, USER_DEACTIVATED, PASSWORD_RESET_BY_ADMIN,
PASSWORD_CHANGE_FORCED. No column type or length change is needed — the
column is already VARCHAR(30), and the longest new value
("password_reset_by_admin", 24 chars) fits.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22faf2677ebe"
down_revision: str | None = "da6db356e430"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ORIGINAL_VALUES = (
    "login_success",
    "login_failed",
    "logout",
    "password_changed",
    "password_reset_requested",
    "password_reset_completed",
    "token_refreshed",
    "token_revoked",
    "token_reuse_detected",
    "account_locked",
    "account_unlocked",
    "role_assigned",
    "role_revoked",
)
_NEW_VALUES = (
    "user_created",
    "user_updated",
    "user_deleted",
    "user_activated",
    "user_deactivated",
    "password_reset_by_admin",
    "password_change_forced",
)


def _in_clause(values: tuple[str, ...]) -> str:
    return "event_type IN (" + ", ".join(f"'{value}'" for value in values) + ")"


def upgrade() -> None:
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _in_clause(_ORIGINAL_VALUES + _NEW_VALUES),
    )


def downgrade() -> None:
    # Fails if any row already has one of the new event_type values —
    # expected and correct: a downgrade that narrows an allowed-value set
    # cannot silently discard data that no longer satisfies it, so an
    # operator must resolve those rows first.
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type", "auth_audit_log", _in_clause(_ORIGINAL_VALUES)
    )
