"""create lab tables

Revision ID: 26d08c008ed7
Revises: 52488f320729
Create Date: 2026-08-27 21:47:35.429098

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26d08c008ed7"
down_revision: str | None = "52488f320729"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_test",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "pathology",
                "radiology",
                name="lab_test_category",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("price > 0", name="ck_lab_test_price_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_lab_test_is_active", "lab_test", ["is_active"], unique=False)
    op.create_index("ix_lab_test_name", "lab_test", ["name"], unique=False)
    op.create_table(
        "lab_bill",
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("queue_token", sa.String(length=20), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_reason", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "unpaid",
                "partially_paid",
                "paid",
                name="lab_bill_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manual_patient_name", sa.String(length=150), nullable=True),
        sa.Column("manual_patient_age", sa.Integer(), nullable=True),
        sa.Column("manual_patient_phone", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(manual_patient_name IS NULL AND manual_patient_age IS NULL "
            "AND manual_patient_phone IS NULL) OR (manual_patient_name IS NOT NULL "
            "AND manual_patient_age IS NOT NULL AND manual_patient_phone IS NOT NULL)",
            name="ck_lab_bill_manual_patient_fields_all_or_none",
        ),
        sa.CheckConstraint(
            "NOT (patient_id IS NOT NULL AND manual_patient_name IS NOT NULL)",
            name="ck_lab_bill_not_both_patient_and_manual",
        ),
        sa.CheckConstraint(
            "amount_paid <= total_amount", name="ck_lab_bill_amount_paid_not_exceeding_total"
        ),
        sa.CheckConstraint("amount_paid >= 0", name="ck_lab_bill_amount_paid_non_negative"),
        sa.CheckConstraint("discount_amount >= 0", name="ck_lab_bill_discount_amount_non_negative"),
        sa.CheckConstraint("total_amount >= 0", name="ck_lab_bill_total_amount_non_negative"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_lab_bill_patient_id", "lab_bill", ["patient_id"], unique=False)
    op.create_index(
        "ix_lab_bill_queue_token_active",
        "lab_bill",
        ["queue_token"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "lab_bill_item",
        sa.Column("lab_bill_id", sa.Uuid(), nullable=False),
        sa.Column("lab_test_id", sa.Uuid(), nullable=False),
        sa.Column("lab_test_name_snapshot", sa.String(length=150), nullable=False),
        sa.Column(
            "category_snapshot",
            sa.Enum(
                "pathology",
                "radiology",
                name="lab_bill_item_category_snapshot",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("unit_price_snapshot", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["lab_bill_id"],
            ["lab_bill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lab_test_id"],
            ["lab_test.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_lab_bill_item_lab_bill_id", "lab_bill_item", ["lab_bill_id"], unique=False)
    op.create_table(
        "lab_bill_payment",
        sa.Column("lab_bill_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "cash",
                "bank_transfer",
                "jazzcash",
                "easypaisa",
                "card",
                name="payment_method",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("amount > 0", name="ck_lab_bill_payment_amount_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["lab_bill_id"],
            ["lab_bill.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_lab_bill_payment_lab_bill_id", "lab_bill_payment", ["lab_bill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lab_bill_payment_lab_bill_id", table_name="lab_bill_payment")
    op.drop_table("lab_bill_payment")
    op.drop_index("ix_lab_bill_item_lab_bill_id", table_name="lab_bill_item")
    op.drop_table("lab_bill_item")
    op.drop_index(
        "ix_lab_bill_queue_token_active",
        table_name="lab_bill",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_lab_bill_patient_id", table_name="lab_bill")
    op.drop_table("lab_bill")
    op.drop_index("ix_lab_test_name", table_name="lab_test")
    op.drop_index("ix_lab_test_is_active", table_name="lab_test")
    op.drop_table("lab_test")
    # ### end Alembic commands ###
