"""create consultation table

Revision ID: 2ed68a19a105
Revises: 81bccb2dae13
Create Date: 2026-08-06 20:27:02.165888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ed68a19a105"
down_revision: str | None = "81bccb2dae13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consultation",
        sa.Column("visit_id", sa.Uuid(), nullable=False),
        sa.Column("doctor_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "awaiting_vitals",
                "completed",
                "cancelled",
                name="consultation_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("prescription", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["doctor_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_consultation_doctor_user_id_status",
        "consultation",
        ["doctor_user_id", "status"],
        unique=False,
    )
    op.create_index("ix_consultation_visit_id", "consultation", ["visit_id"], unique=False)
    op.create_index(
        "ix_consultation_visit_id_active",
        "consultation",
        ["visit_id"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('in_progress', 'awaiting_vitals')"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_consultation_visit_id_active",
        table_name="consultation",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('in_progress', 'awaiting_vitals')"
        ),
    )
    op.drop_index("ix_consultation_visit_id", table_name="consultation")
    op.drop_index("ix_consultation_doctor_user_id_status", table_name="consultation")
    op.drop_table("consultation")
    # ### end Alembic commands ###
