"""create inventory tables

Revision ID: 34031b5db2af
Revises: 4ad5462d0835
Create Date: 2026-08-26 11:45:23.420165

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34031b5db2af"
down_revision: str | None = "4ad5462d0835"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_item",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "medicine",
                "injection",
                "drip",
                "equipment",
                name="inventory_category",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "unit",
            sa.Enum(
                "piece",
                "box",
                "bottle",
                "vial",
                "ampoule",
                "ml",
                name="inventory_unit",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("low_stock_threshold", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("main_stock_level", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("emergency_stock_level", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "emergency_stock_level >= 0",
            name="ck_inventory_item_emergency_stock_level_non_negative",
        ),
        sa.CheckConstraint(
            "low_stock_threshold IS NULL OR low_stock_threshold >= 0",
            name="ck_inventory_item_low_stock_threshold_non_negative",
        ),
        sa.CheckConstraint(
            "main_stock_level >= 0", name="ck_inventory_item_main_stock_level_non_negative"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_inventory_item_category", "inventory_item", ["category"], unique=False)
    op.create_index("ix_inventory_item_is_active", "inventory_item", ["is_active"], unique=False)
    op.create_index("ix_inventory_item_name", "inventory_item", ["name"], unique=False)
    op.create_table(
        "inventory_main_stock_receipt",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "quantity > 0", name="ck_inventory_main_stock_receipt_quantity_positive"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_item.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_main_stock_receipt_item_id",
        "inventory_main_stock_receipt",
        ["item_id"],
        unique=False,
    )
    op.create_table(
        "inventory_transfer",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("transferred_on", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("quantity > 0", name="ck_inventory_transfer_quantity_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_item.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_transfer_item_id", "inventory_transfer", ["item_id"], unique=False
    )
    op.create_table(
        "inventory_usage_entry",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("used_on", sa.Date(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("manual_patient_name", sa.String(length=150), nullable=True),
        sa.Column("manual_patient_age", sa.Integer(), nullable=True),
        sa.Column("manual_patient_phone", sa.String(length=20), nullable=True),
        sa.Column("reason_note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(manual_patient_name IS NULL AND manual_patient_age IS NULL "
            "AND manual_patient_phone IS NULL) OR (manual_patient_name IS NOT NULL "
            "AND manual_patient_age IS NOT NULL AND manual_patient_phone IS NOT NULL)",
            name="ck_inventory_usage_entry_manual_patient_fields_all_or_none",
        ),
        sa.CheckConstraint(
            "NOT (patient_id IS NOT NULL AND manual_patient_name IS NOT NULL)",
            name="ck_inventory_usage_entry_not_both_patient_and_manual",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_inventory_usage_entry_quantity_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_usage_entry_created_at", "inventory_usage_entry", ["created_at"], unique=False
    )
    op.create_index(
        "ix_inventory_usage_entry_item_id", "inventory_usage_entry", ["item_id"], unique=False
    )
    op.create_index(
        "ix_inventory_usage_entry_patient_id", "inventory_usage_entry", ["patient_id"], unique=False
    )
    op.create_table(
        "inventory_restock_request",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "fulfilled",
                "rejected",
                name="inventory_restock_request_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("fulfilled_by_transfer_id", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=200), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "requested_quantity IS NULL OR requested_quantity > 0",
            name="ck_inventory_restock_request_requested_quantity_positive",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["fulfilled_by_transfer_id"],
            ["inventory_transfer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_item.id"],
        ),
        sa.ForeignKeyConstraint(["resolved_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_restock_request_item_id",
        "inventory_restock_request",
        ["item_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_restock_request_status_created_at",
        "inventory_restock_request",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_inventory_restock_request_status_created_at", table_name="inventory_restock_request"
    )
    op.drop_index("ix_inventory_restock_request_item_id", table_name="inventory_restock_request")
    op.drop_table("inventory_restock_request")
    op.drop_index("ix_inventory_usage_entry_patient_id", table_name="inventory_usage_entry")
    op.drop_index("ix_inventory_usage_entry_item_id", table_name="inventory_usage_entry")
    op.drop_index("ix_inventory_usage_entry_created_at", table_name="inventory_usage_entry")
    op.drop_table("inventory_usage_entry")
    op.drop_index("ix_inventory_transfer_item_id", table_name="inventory_transfer")
    op.drop_table("inventory_transfer")
    op.drop_index(
        "ix_inventory_main_stock_receipt_item_id", table_name="inventory_main_stock_receipt"
    )
    op.drop_table("inventory_main_stock_receipt")
    op.drop_index("ix_inventory_item_name", table_name="inventory_item")
    op.drop_index("ix_inventory_item_is_active", table_name="inventory_item")
    op.drop_index("ix_inventory_item_category", table_name="inventory_item")
    op.drop_table("inventory_item")
    # ### end Alembic commands ###
