"""extend auth_audit_event_type for role management events

Revision ID: 642dc9d7eb70
Revises: 22faf2677ebe
Create Date: 2026-08-06 04:11:31.712060

Hand-written, not autogenerated — same reasoning as
22faf2677ebe_extend_auth_audit_event_type_for_user_.py: Alembic's
autogenerate does not diff the SQL body of an existing named CHECK
constraint, so `auth_audit_log.event_type`'s constraint (backing
`sa.Enum(..., native_enum=False, create_constraint=True)`) must be
dropped and recreated by hand to add the 3 new `AuditEventType` members
introduced for the Role Management module (Phase 5 Step 3):
ROLE_CREATED, ROLE_UPDATED, ROLE_DELETED. No column type or length
change is needed — the column is already VARCHAR(30), and the longest
new value ("role_created", 12 chars) fits comfortably.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "642dc9d7eb70"
down_revision: str | None = "22faf2677ebe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREVIOUS_VALUES = (
    "login_success",
    "login_failed",
    "logout",
    "password_changed",
    "password_reset_requested",
    "password_reset_completed",
    "token_refreshed",
    "token_revoked",
    "token_reuse_detected",
    "account_locked",
    "account_unlocked",
    "role_assigned",
    "role_revoked",
    "user_created",
    "user_updated",
    "user_deleted",
    "user_activated",
    "user_deactivated",
    "password_reset_by_admin",
    "password_change_forced",
)
_NEW_VALUES = (
    "role_created",
    "role_updated",
    "role_deleted",
)


def _in_clause(values: tuple[str, ...]) -> str:
    return "event_type IN (" + ", ".join(f"'{value}'" for value in values) + ")"


def upgrade() -> None:
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _in_clause(_PREVIOUS_VALUES + _NEW_VALUES),
    )


def downgrade() -> None:
    # Fails if any row already has one of the new event_type values —
    # expected and correct: a downgrade that narrows an allowed-value set
    # cannot silently discard data that no longer satisfies it, so an
    # operator must resolve those rows first.
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type", "auth_audit_log", _in_clause(_PREVIOUS_VALUES)
    )
