"""create queue_entry table

Revision ID: 81bccb2dae13
Revises: c921bf9b05ee
Create Date: 2026-08-06 19:54:14.893230

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81bccb2dae13"
down_revision: str | None = "c921bf9b05ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_entry",
        sa.Column("visit_id", sa.Uuid(), nullable=False),
        sa.Column(
            "destination",
            sa.Enum(
                "reception",
                "vitals",
                "doctor",
                name="queue_destination",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "in_progress",
                "completed",
                "cancelled",
                name="queue_entry_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_queue_entry_destination_status", "queue_entry", ["destination", "status"], unique=False
    )
    op.create_index("ix_queue_entry_visit_id", "queue_entry", ["visit_id"], unique=False)
    op.create_index(
        "ix_queue_entry_visit_id_active",
        "queue_entry",
        ["visit_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND left_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_queue_entry_visit_id_active",
        table_name="queue_entry",
        postgresql_where=sa.text("deleted_at IS NULL AND left_at IS NULL"),
    )
    op.drop_index("ix_queue_entry_visit_id", table_name="queue_entry")
    op.drop_index("ix_queue_entry_destination_status", table_name="queue_entry")
    op.drop_table("queue_entry")
    # ### end Alembic commands ###
