"""create pharmacy tables

Revision ID: a08c97460b1f
Revises: 0c928477b446
Create Date: 2026-08-11 21:22:16.925393

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a08c97460b1f"
down_revision: str | None = "0c928477b446"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medicine",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "sachet",
                "drops",
                "tablet",
                "injection",
                name="medicine_category",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("unit_price > 0", name="ck_medicine_unit_price_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_medicine_is_active", "medicine", ["is_active"], unique=False)
    op.create_index("ix_medicine_name", "medicine", ["name"], unique=False)
    op.create_table(
        "medicine_bill",
        sa.Column("visit_id", sa.Uuid(), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("total_amount >= 0", name="ck_medicine_bill_total_amount_non_negative"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_medicine_bill_visit_id", "medicine_bill", ["visit_id"], unique=False)
    op.create_table(
        "medicine_bill_item",
        sa.Column("medicine_bill_id", sa.Uuid(), nullable=False),
        sa.Column("medicine_id", sa.Uuid(), nullable=False),
        sa.Column("medicine_name_snapshot", sa.String(length=150), nullable=False),
        sa.Column(
            "category_snapshot",
            sa.Enum(
                "sachet",
                "drops",
                "tablet",
                "injection",
                name="medicine_bill_item_category_snapshot",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("unit_price_snapshot", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("line_total >= 0", name="ck_medicine_bill_item_line_total_non_negative"),
        sa.CheckConstraint("quantity > 0", name="ck_medicine_bill_item_quantity_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["medicine_bill_id"],
            ["medicine_bill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medicine_id"],
            ["medicine.id"],
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_medicine_bill_item_medicine_bill_id",
        "medicine_bill_item",
        ["medicine_bill_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_medicine_bill_item_medicine_bill_id", table_name="medicine_bill_item")
    op.drop_table("medicine_bill_item")
    op.drop_index("ix_medicine_bill_visit_id", table_name="medicine_bill")
    op.drop_table("medicine_bill")
    op.drop_index("ix_medicine_name", table_name="medicine")
    op.drop_index("ix_medicine_is_active", table_name="medicine")
    op.drop_table("medicine")
    # ### end Alembic commands ###
