"""add permission display_name and extend auth_audit_event_type for permission management

Revision ID: a6f7293e7d51
Revises: 642dc9d7eb70
Create Date: 2026-08-06 04:57:55.806941

Two changes, both required for the Permission Management module (Phase
5 Step 4), kept in one revision since they're a single logical unit of
schema change for that feature:

1. `permission.display_name` — a new `NOT NULL` column. Autogenerate
   correctly detects the column itself but (as always) emits a direct
   `nullable=False`, which would fail outright against this table's
   existing rows (11 permission rows already exist from Phase 5 Steps 2
   and 3's `roles:*`/`users:*` codes). This migration instead adds the
   column nullable, backfills every existing row with a value derived
   from its `code` (title-cased action segment, e.g. "users:manage_password"
   -> "Manage Password" — a reasonable default for pre-existing
   reference-data rows; every row created through the API from this
   point on always supplies a real value, since `display_name` is a
   required field on `CreatePermissionRequest`), then enforces `NOT
   NULL`. Downgrade drops the column outright — going back to a schema
   without it is definitionally a data-discarding operation, same as
   any other "add column" migration's reverse.

2. `auth_audit_log.event_type`'s CHECK constraint — hand-written, not
   autogenerated, for the same reason as 22faf2677ebe and 642dc9d7eb70:
   Alembic's autogenerate does not diff the SQL body of an existing
   named CHECK constraint backing `sa.Enum(..., native_enum=False)`.
   Adds PERMISSION_CREATED/UPDATED/DELETED (26 total allowed values).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6f7293e7d51"
down_revision: str | None = "642dc9d7eb70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREVIOUS_EVENT_TYPE_VALUES = (
    "login_success",
    "login_failed",
    "logout",
    "password_changed",
    "password_reset_requested",
    "password_reset_completed",
    "token_refreshed",
    "token_revoked",
    "token_reuse_detected",
    "account_locked",
    "account_unlocked",
    "role_assigned",
    "role_revoked",
    "user_created",
    "user_updated",
    "user_deleted",
    "user_activated",
    "user_deactivated",
    "password_reset_by_admin",
    "password_change_forced",
    "role_created",
    "role_updated",
    "role_deleted",
)
_NEW_EVENT_TYPE_VALUES = (
    "permission_created",
    "permission_updated",
    "permission_deleted",
)


def _event_type_in_clause(values: tuple[str, ...]) -> str:
    return "event_type IN (" + ", ".join(f"'{value}'" for value in values) + ")"


def upgrade() -> None:
    # 1. permission.display_name — add nullable, backfill, enforce NOT NULL.
    op.add_column("permission", sa.Column("display_name", sa.String(length=150), nullable=True))
    op.execute(
        """
        UPDATE permission
        SET display_name = INITCAP(REPLACE(SPLIT_PART(code, ':', 2), '_', ' '))
        WHERE display_name IS NULL
        """
    )
    op.alter_column("permission", "display_name", nullable=False)

    # 2. auth_audit_event_type CHECK constraint expansion.
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _event_type_in_clause(_PREVIOUS_EVENT_TYPE_VALUES + _NEW_EVENT_TYPE_VALUES),
    )


def downgrade() -> None:
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _event_type_in_clause(_PREVIOUS_EVENT_TYPE_VALUES),
    )

    op.drop_column("permission", "display_name")
