"""create patient and audit_log tables

Revision ID: ad00270104a4
Revises: 1d509f51cca2
Create Date: 2026-08-06 19:05:25.322828

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad00270104a4"
down_revision: str | None = "1d509f51cca2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Backs Patient.mr_number generation (see
# app/modules/patients/repository.py's PatientRepository.
# next_mr_number_value) — a real database sequence rather than a
# count-then-increment, so concurrent registrations at multiple
# Reception counters can never collide on the same MR number.
_MR_NUMBER_SEQUENCE = "patient_mr_number_seq"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_actor_user_id", "audit_log", ["actor_user_id"], unique=False)
    op.create_index(
        "ix_audit_log_entity_type_entity_id_created_at",
        "audit_log",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_module_action_created_at",
        "audit_log",
        ["module", "action", "created_at"],
        unique=False,
    )

    # ### patient table ###
    op.create_table(
        "patient",
        sa.Column("mr_number", sa.String(length=20), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("guardian_name", sa.String(length=150), nullable=True),
        sa.Column(
            "gender",
            sa.Enum(
                "female",
                "male",
                "other",
                name="patient_gender",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("approximate_age_years", sa.Integer(), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("cnic", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_patient_cnic_active",
        "patient",
        ["cnic"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_patient_full_name", "patient", ["full_name"], unique=False)
    op.create_index(
        "ix_patient_mr_number_active",
        "patient",
        ["mr_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_patient_phone_number", "patient", ["phone_number"], unique=False)

    # ### mr_number sequence — not table-attached, autogenerate can't see it ###
    op.execute(f"CREATE SEQUENCE {_MR_NUMBER_SEQUENCE} START WITH 1 INCREMENT BY 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP SEQUENCE {_MR_NUMBER_SEQUENCE}")

    op.drop_index("ix_patient_phone_number", table_name="patient")
    op.drop_index(
        "ix_patient_mr_number_active",
        table_name="patient",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_patient_full_name", table_name="patient")
    op.drop_index(
        "ix_patient_cnic_active",
        table_name="patient",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("patient")

    op.drop_index("ix_audit_log_module_action_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_entity_type_entity_id_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_user_id", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
