"""add invoice single open per visit constraint

Revision ID: c42408d9c420
Revises: f3e7aafe88ac
Create Date: 2026-08-07 00:01:19.576996

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c42408d9c420"
down_revision: str | None = "f3e7aafe88ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_invoice_visit_id_open_active",
        "invoice",
        ["visit_id"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('pending_payment', 'partially_paid')"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_invoice_visit_id_open_active",
        table_name="invoice",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('pending_payment', 'partially_paid')"
        ),
    )
    # ### end Alembic commands ###
