"""create visit table

Revision ID: c921bf9b05ee
Revises: ad00270104a4
Create Date: 2026-08-06 19:29:53.574184

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c921bf9b05ee"
down_revision: str | None = "ad00270104a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Backs Visit.queue_token generation (see
# app/modules/visits/repository.py's VisitRepository.
# next_queue_token_value) — mirrors patients' MR-number sequence exactly.
_QUEUE_TOKEN_SEQUENCE = "visit_queue_token_seq"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "visit",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("doctor_user_id", sa.Uuid(), nullable=False),
        sa.Column("queue_token", sa.String(length=20), nullable=False),
        sa.Column("procedure", sa.String(length=200), nullable=False),
        sa.Column("vitals_required", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "registered",
                "waiting_vitals",
                "waiting_doctor",
                "in_consultation",
                "waiting_billing",
                "payment_pending",
                "completed",
                "cancelled",
                name="visit_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["doctor_user_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"]),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_visit_doctor_user_id", "visit", ["doctor_user_id"], unique=False)
    op.create_index("ix_visit_patient_id", "visit", ["patient_id"], unique=False)
    op.create_index(
        "ix_visit_queue_token_active",
        "visit",
        ["queue_token"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_visit_status", "visit", ["status"], unique=False)

    # ### queue_token sequence — not table-attached, autogenerate can't see it ###
    op.execute(f"CREATE SEQUENCE {_QUEUE_TOKEN_SEQUENCE} START WITH 1 INCREMENT BY 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP SEQUENCE {_QUEUE_TOKEN_SEQUENCE}")

    op.drop_index("ix_visit_status", table_name="visit")
    op.drop_index(
        "ix_visit_queue_token_active",
        table_name="visit",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_visit_patient_id", table_name="visit")
    op.drop_index("ix_visit_doctor_user_id", table_name="visit")
    op.drop_table("visit")
    # ### end Alembic commands ###
