"""add self-service signup: pending status states, otp_code table, user shift

Revision ID: d1fb51975400
Revises: 6a82986a4db0
Create Date: 2026-08-08 03:53:06.824778

Combines an autogenerated part (the new `otp_code` table and `user.shift`
column — both diffed correctly by Alembic) with two hand-written CHECK
constraint replacements, same reasoning as
642dc9d7eb70_extend_auth_audit_event_type_for_role_.py: Alembic's
autogenerate does not diff the SQL body of an existing named CHECK
constraint backing a `sa.Enum(..., native_enum=False, create_constraint=True)`
column, so `user.status` (three new self-service-signup states:
pending_email_verification, pending_admin_approval, rejected — see
UserStatus's own docstring for why PENDING_VERIFICATION isn't reused) and
`auth_audit_log.event_type` (four new signup-lifecycle events) must both be
dropped and recreated by hand.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1fb51975400"
down_revision: str | None = "6a82986a4db0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PREVIOUS_USER_STATUS_VALUES = (
    "active",
    "inactive",
    "suspended",
    "locked",
    "pending_verification",
)
_NEW_USER_STATUS_VALUES = (
    "pending_email_verification",
    "pending_admin_approval",
    "rejected",
)

_PREVIOUS_AUDIT_EVENT_TYPE_VALUES = (
    "login_success",
    "login_failed",
    "logout",
    "password_changed",
    "password_reset_requested",
    "password_reset_completed",
    "token_refreshed",
    "token_revoked",
    "token_reuse_detected",
    "account_locked",
    "account_unlocked",
    "role_assigned",
    "role_revoked",
    "user_created",
    "user_updated",
    "user_deleted",
    "user_activated",
    "user_deactivated",
    "password_reset_by_admin",
    "password_change_forced",
    "role_created",
    "role_updated",
    "role_deleted",
    "permission_created",
    "permission_updated",
    "permission_deleted",
    "permission_granted",
    "permission_revoked",
)
_NEW_AUDIT_EVENT_TYPE_VALUES = (
    "user_signed_up",
    "email_verified",
    "signup_approved",
    "signup_rejected",
)


def _in_clause(column: str, values: tuple[str, ...]) -> str:
    return f"{column} IN (" + ", ".join(f"'{value}'" for value in values) + ")"


def upgrade() -> None:
    op.create_table(
        "otp_code",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "email_verification",
                "password_reset",
                name="otp_purpose",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_otp_code_expires_at", "otp_code", ["expires_at"], unique=False)
    op.create_index(
        "ix_otp_code_user_id_purpose_active",
        "otp_code",
        ["user_id", "purpose"],
        unique=True,
        postgresql_where=sa.text("consumed_at IS NULL"),
    )
    op.add_column(
        "user",
        sa.Column(
            "shift",
            sa.Enum(
                "morning",
                "night",
                name="user_shift",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=True,
        ),
    )

    op.drop_constraint("user_status", "user", type_="check")
    op.create_check_constraint(
        "user_status",
        "user",
        _in_clause("status", _PREVIOUS_USER_STATUS_VALUES + _NEW_USER_STATUS_VALUES),
    )

    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _in_clause("event_type", _PREVIOUS_AUDIT_EVENT_TYPE_VALUES + _NEW_AUDIT_EVENT_TYPE_VALUES),
    )


def downgrade() -> None:
    # Fails if any row already uses a new value — expected and correct,
    # same reasoning as every prior enum-narrowing downgrade in this
    # history: an operator must resolve those rows first.
    op.drop_constraint("auth_audit_event_type", "auth_audit_log", type_="check")
    op.create_check_constraint(
        "auth_audit_event_type",
        "auth_audit_log",
        _in_clause("event_type", _PREVIOUS_AUDIT_EVENT_TYPE_VALUES),
    )

    op.drop_constraint("user_status", "user", type_="check")
    op.create_check_constraint(
        "user_status", "user", _in_clause("status", _PREVIOUS_USER_STATUS_VALUES)
    )

    op.drop_column("user", "shift")
    op.drop_index(
        "ix_otp_code_user_id_purpose_active",
        table_name="otp_code",
        postgresql_where=sa.text("consumed_at IS NULL"),
    )
    op.drop_index("ix_otp_code_expires_at", table_name="otp_code")
    op.drop_table("otp_code")
