"""create permission, role_permission, user_role, refresh_token,
login_session, password_history, auth_audit_log tables

Revision ID: da6db356e430
Revises: eaa9f09ece9f
Create Date: 2026-08-04 08:07:49.275909

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da6db356e430"
down_revision: str | None = "eaa9f09ece9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_audit_log",
        sa.Column(
            "event_type",
            sa.Enum(
                "login_success",
                "login_failed",
                "logout",
                "password_changed",
                "password_reset_requested",
                "password_reset_completed",
                "token_refreshed",
                "token_revoked",
                "token_reuse_detected",
                "account_locked",
                "account_unlocked",
                "role_assigned",
                "role_revoked",
                name="auth_audit_event_type",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("target_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "failure",
                name="auth_audit_event_status",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_auth_audit_log_actor_user_id", "auth_audit_log", ["actor_user_id"], unique=False
    )
    op.create_index(
        "ix_auth_audit_log_event_type_created_at",
        "auth_audit_log",
        ["event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_auth_audit_log_target_user_id_created_at",
        "auth_audit_log",
        ["target_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "password_history",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_password_history_user_id_created_at",
        "password_history",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "permission",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("group", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_permission_code_active",
        "permission",
        ["code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_permission_group", "permission", ["group"], unique=False)
    op.create_table(
        "refresh_token",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "revoked_reason",
            sa.Enum(
                "logout",
                "rotated",
                "reuse_detected",
                "admin_revoked",
                "password_changed",
                name="refresh_token_revoked_reason",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("device_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL) = (revoked_reason IS NULL)",
            name="ck_refresh_token_revoked_at_reason_paired",
        ),
        sa.CheckConstraint("expires_at > created_at", name="ck_refresh_token_expires_after_issued"),
        sa.ForeignKeyConstraint(["replaced_by_id"], ["refresh_token.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_refresh_token_expires_at", "refresh_token", ["expires_at"], unique=False)
    op.create_index("ix_refresh_token_family_id", "refresh_token", ["family_id"], unique=False)
    op.create_index("ix_refresh_token_token_hash", "refresh_token", ["token_hash"], unique=True)
    op.create_index(
        "ix_refresh_token_user_id_active",
        "refresh_token",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "login_session",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_id", sa.Uuid(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("device_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("remember_me", sa.Boolean(), nullable=False),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("logout_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "logout_reason",
            sa.Enum(
                "user_logout",
                "expired",
                "revoked",
                "forced",
                name="login_session_logout_reason",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(logout_at IS NULL) = (logout_reason IS NULL)",
            name="ck_login_session_logout_at_reason_paired",
        ),
        sa.CheckConstraint(
            "logout_at IS NULL OR logout_at >= created_at",
            name="ck_login_session_logout_at_after_login",
        ),
        sa.ForeignKeyConstraint(["refresh_token_id"], ["refresh_token.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_login_session_last_activity_at_active",
        "login_session",
        ["last_activity_at"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        "ix_login_session_user_id_active",
        "login_session",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["permission_id"], ["permission.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_role_permission_permission_id", "role_permission", ["permission_id"], unique=False
    )
    op.create_index("ix_role_permission_role_id", "role_permission", ["role_id"], unique=False)
    op.create_index(
        "ix_role_permission_role_id_permission_id_active",
        "role_permission",
        ["role_id", "permission_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_role_expires_at",
        "user_role",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.create_index("ix_user_role_role_id", "user_role", ["role_id"], unique=False)
    op.create_index("ix_user_role_user_id", "user_role", ["user_id"], unique=False)
    op.create_index(
        "ix_user_role_user_id_role_id_active",
        "user_role",
        ["user_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_role_user_id_role_id_active",
        table_name="user_role",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_user_role_user_id", table_name="user_role")
    op.drop_index("ix_user_role_role_id", table_name="user_role")
    op.drop_index(
        "ix_user_role_expires_at",
        table_name="user_role",
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.drop_table("user_role")
    op.drop_index(
        "ix_role_permission_role_id_permission_id_active",
        table_name="role_permission",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_role_permission_role_id", table_name="role_permission")
    op.drop_index("ix_role_permission_permission_id", table_name="role_permission")
    op.drop_table("role_permission")
    op.drop_index(
        "ix_login_session_user_id_active",
        table_name="login_session",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(
        "ix_login_session_last_activity_at_active",
        table_name="login_session",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("login_session")
    op.drop_index(
        "ix_refresh_token_user_id_active",
        table_name="refresh_token",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_refresh_token_token_hash", table_name="refresh_token")
    op.drop_index("ix_refresh_token_family_id", table_name="refresh_token")
    op.drop_index("ix_refresh_token_expires_at", table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index("ix_permission_group", table_name="permission")
    op.drop_index(
        "ix_permission_code_active",
        table_name="permission",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("permission")
    op.drop_index("ix_password_history_user_id_created_at", table_name="password_history")
    op.drop_table("password_history")
    op.drop_index("ix_auth_audit_log_target_user_id_created_at", table_name="auth_audit_log")
    op.drop_index("ix_auth_audit_log_event_type_created_at", table_name="auth_audit_log")
    op.drop_index("ix_auth_audit_log_actor_user_id", table_name="auth_audit_log")
    op.drop_table("auth_audit_log")
    # ### end Alembic commands ###
